baseDomain: apps.sno.example
additionalRoutes:
  - name: toy-service-echo-via-web
    host: svc-web.apps.sno.example
    path: /echo

# Override image per env to ensure deterministic tag shape
image:
  repository: quay.io/paulcapestany/toy-service
  tag: v0.3.39-commit.8a1475e
