baseDomain: apps-crc.testing
healthPath: "/healthz"
additionalRoutes:
  - name: toy-service-echo-via-web
    host: svc-web.apps-crc.testing
    path: /echo
image:
  repository: quay.io/paulcapestany/toy-service
  tag: v0.3.38-commit.c709549
backend:
  secretMount:
    reloadSidecar:
      enabled: true
      webhookUrl: http://127.0.0.1:8080/-/reload
