route:
  enabled: true
  host: signet.ing
  clusterIssuerName: letsencrypt-dns01-route53-local

ingress:
  enabled: false
  className: ""
  tlsSecretName: ""
  clusterIssuerName: ""

# Use existing Quay pull secret for private image pulls in local
imagePullSecrets:
  - quay-auth
