image:
  repository: quay.io/paulcapestany/signet-landing
  tag: "0.1.4"
  pullPolicy: IfNotPresent
imagePullSecrets: []

replicaCount: 1
service:
  port: 8080
  type: ClusterIP

route:
  enabled: false
  host: ""
  clusterIssuerName: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  tlsSecretName: ""
  clusterIssuerName: ""
