image:
  repository: quay.io/paulcapestany/signet-landing
  tag: "v0.1.9-commit.g428cf12"
  pullPolicy: IfNotPresent
imagePullSecrets: []
replicaCount: 1
service:
  port: 8080
  type: ClusterIP
route:
  enabled: true
  host: signet.ing # explicit FQDN
  clusterIssuerName: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  tlsSecretName: ""
  clusterIssuerName: ""
