route:
  enabled: true
  host: signet.ing
  clusterIssuerName: letsencrypt-dns01-route53-local

ingress:
  enabled: false
  className: ""
  tlsSecretName: ""
  clusterIssuerName: ""

# Repo is public; no pull secret needed in local
imagePullSecrets: []
