route:
  enabled: false
  host: signet.ing
  clusterIssuerName: letsencrypt-dns01-route53-local

ingress:
  enabled: true
  className: ""
  tlsSecretName: signet-landing-tls
  clusterIssuerName: letsencrypt-dns01-route53-local
  additionalHosts:
    - www.signet.ing

# Repo is public; no pull secret needed in local
imagePullSecrets: []
