model:
  storageUri: hf://Qwen/Qwen2.5-14B-Instruct
  env:
    - name: LD_LIBRARY_PATH
      value: "/usr/local/nvidia/lib64:/usr/local/nvidia/lib:$(LD_LIBRARY_PATH)"
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
predictor:
  runtimeClassName: nvidia-cdi
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
runtime:
  container:
    env:
      - name: LD_LIBRARY_PATH
        value: "/usr/local/nvidia/lib64:/usr/local/nvidia/lib:$(LD_LIBRARY_PATH)"
