model:
  storageUri: hf://Qwen/Qwen2.5-14B-Instruct
predictor:
  runtimeClassName: nvidia-cdi
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
