baseDomain: ""
image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.25-alpine
  pullPolicy: IfNotPresent

replicaCount: 1
service:
  port: 8080
  type: ClusterIP

route:
  enabled: true
  host: ""  # explicit FQDN
  clusterIssuerName: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  tlsSecretName: ""
  clusterIssuerName: ""
