baseDomain: apps-crc.testing
route:
  enabled: true
  host: "alpha.cyphai.com"
  clusterIssuerName: letsencrypt-dns01-route53-cyphai

ingress:
  enabled: false
  className: openshift-default
  tlsSecretName: nostr-site-tls
  clusterIssuerName: letsencrypt-http01-local
