apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-signet
  namespace: bitiq-local
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-route53-local
spec:
  tls:
    - hosts:
        - signet.ing
        - www.signet.ing
      secretName: nginx-signet-tls
  rules:
    - host: signet.ing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080
    - host: www.signet.ing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 8080
