replicaCount: 0

env:
  llmBaseUrl: "http://signet-llm-predictor.bitiq-prod.svc.cluster.local:8080"
  embeddingsBaseUrl: "http://signet-embeddings-predictor.bitiq-prod.svc.cluster.local:8080"
  token:
    secretName: ""
