argoNamespace: openshift-gitops
logLevel: debug

argocd:
  server: openshift-gitops-server
  port: 443
  insecure: true
  # When secret.create=true below, set the token here or via env/CI
  token: ""

image:
  repository: quay.io/argoprojlabs/argocd-image-updater
  tag: v0.16.0
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
secret:
  create: false
  name: argocd-image-updater-secret
  key: token
