image:
  tag: v0.1.2-commit.3874f8c
  pullPolicy: Always

env:
  envPrefix: dev
  gitCommitHash: 3874f8c
  ollamaHost: https://ollama.cyphai.com

networkPolicy:
  egress:
    dnsCIDRs:
      - 10.217.4.0/23
