model:
  storageUri: hf://intfloat/e5-mistral-7b-instruct
predictor:
  runtimeClassName: nvidia
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
