model:
  storageUri: hf://intfloat/e5-mistral-7b-instruct
  env:
    - name: LD_LIBRARY_PATH
      value: "/usr/lib64:/usr/local/nvidia/lib64:/usr/local/nvidia/lib"
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
predictor:
  runtimeClassName: nvidia-legacy
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
